version: '2'

services:
  # Backend API
  review-component:
    container_name: review-server
    build: ./
    command: npm start
    working_dir: /app
    env_file:
      - ./server/config/.env
    ports:
      - "3002:3002"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/reviews
      REDIS_URI: redis://redis:6379
    depends_on:
      - postgres
      - redis

  # Postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/reviews
      POSTGRES_DB: reviews
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
