version: '2'

services:
  # Postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/reviews
      POSTGRES_DB: reviews
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Backend API
  review-component:
    container_name: review-server
    build: ./
    working_dir: /app
    env_file:
      - ./server/config/.env
    ports:
      - "3002:3002"
    depends_on:
      - "postgres"
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
